gitlab:
  - tokenEnvVar: "GITLAB_API_TOKEN"
    hostName: 'gitlab.controlant.com'
    cloneDirectory: '/Users/gudlaugur.egilsson/src/controlant' # Use full path only. Shell expansion not supported (f.ex. ~)
    groups:
      - id: "catapult"
      - id: "DevOps"

    projects:
      - name: "Notes"
        fullPath: "gudlaugur.egilsson/notes"
      - name: "Tools"
        fullPath: "gudlaugur.egilsson/tools"
      - name: "test-automation-reporter"
        fullPath: "qaet/test-automation-reporter"
      - name: "ci-central"
        fullPath: "qaet/ci-central"
        