name: Build and Release

on:
  push:
    branches:
      - test-release-branch
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.23.x]
        os: [macos-latest]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            GOOS=linux GOARCH=${{ matrix.arch }} go build -o gcm-${{ matrix.arch }}
          else
            GOOS=darwin GOARCH=${{ matrix.arch }} go build -o gcm-${{ matrix.arch }}
          fi

      - name: Archive binary
        run: |
          mkdir -p release
          cp gcm-${{ matrix.arch }} release/
          tar -czvf release/gcm-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C release gcm-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcm-${{ matrix.os }}-${{ matrix.arch }}
          path: release/gcm-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: gcm-ubuntu-latest-amd64
          path: ./release
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: gcm-ubuntu-latest-arm64
          path: ./release
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: gcm-macos-latest-amd64
          path: ./release
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: gcm-macos-latest-arm64
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/gcm-ubuntu-latest-amd64.tar.gz
            release/gcm-ubuntu-latest-arm64.tar.gz
            release/gcm-macos-latest-amd64.tar.gz
            release/gcm-macos-latest-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}